### Get Metadata by ID
GET http://localhost:8080/meta?query={findOne(id:"1"){id, name, type}}

### Filter by Meta value
GET http://localhost:8080/meta?query={filter(doctype:"driver card"){id,name,type}}